### ISSUE TITLE
Cannot setup the application by myself 

### ISSUE THREAD

**Issue by itssamrat** [P7h/StormTweetsSentimentAnalysis#1]
Hi Prashanth ,

I am very new to Big Data , Hadoop and also any real time processing tools
like storm and spark.

I am interested to learn how to setup a working twitter sentiment analysis
system. I have cloned your github repository to my laptop but I am unable
to get it working because i don't know how to.

If you have a installation manual or some basic steps/guidance handy , can
you please share the same with me.. That will be very helpful

Thanks ,
Samrat

**Comment by itssamrat** [comment]
Update :  I downloaded Intelli J Idea and then imported the maven project after cloning the repository in desktop. Then i build the project .build was also successful. But how do I run the project and see the ouptut ??

I also created the Twitter Authorization key and secrets as well as the Bing API Key and I updated the config properties with the values.

Please help ..

**Comment by P7h** [comment]
Hi Samrat,

You don't need to setup or install anything other than Maven and JDK to run this code. 
README has detailed documentation with elaborate steps and prerequisites for the execution.

For execution of the code, please follow the steps mentioned for the [local mode](https://github.com/P7h/StormTweetsSentimentAnalysis#local-mode).

Regards,
Prashanth.

**Comment by P7h** [comment]
Samrat,

Can we close this issue, if you were able to get it working?

Regards,
Prashanth.

**Comment by P7h** [comment]
Samrat,

Just checking again to see if we can close this issue.

Regards,
Prashanth.
