### ISSUE TITLE
I'm not able to access the results

### ISSUE THREAD

**Issue by pbasanta** [P7h/StormTweetsSentimentAnalysis#2]
I run your code with:

pbasanta@picara:~/senanal/StormTweetsSentimentAnalysis$ mvn clean compile exec:java -Dexec.classpathScope=compile -Dexec.mainClass=org.p7h.storm.sentimentanalysis.topology.SentimentAnalysisTopology

But I do not understand how to access the results.  It seems as if the engines was not producing any results. Where is the output of the program displayed?

Thanks,
Pablo

**Comment by P7h** [comment]
Hi Pablo,

Hope you followed all the steps detailed in the README of the project.
More so the steps under [Configuration](https://github.com/P7h/StormTweetsSentimentAnalysis#configuration) section. If you have configured Twitter Streaming API Credentials, Bing Maps API, then tweets are processed and the output is displayed - every 30 seconds - on the console and also to a log file using the Logback framework. 

You can browse the code for the output, [in this method](https://github.com/P7h/StormTweetsSentimentAnalysis/blob/master/src/main/java/org/p7h/storm/sentimentanalysis/bolts/SentimentCalculatorBolt.java#L141-L165).
Hope this helps.

Regards,
Prashanth.

**Comment by pbasanta** [comment]
Yeap.
I used 
mvn clean compile exec:java -Dexec.classpathScope=compile -Dexec.mainClass=org.p7h.storm.sentimentanalysis.topology.SentimentAnalysisTopology


The credentials are Ok.  Which is the fault file in which information is stored? Probably, it is this issue.


Thanks,
Pablo

**Comment by P7h** [comment]
Logback is used for logging of messages / errors in [StormTweetsSentimentAnalysis.log](https://github.com/P7h/StormTweetsSentimentAnalysis/blob/master/src/main/resources/logback.xml#L11) in the root of the repo or from where you invoked the maven command.
The default logging level is [INFO](https://github.com/P7h/StormTweetsSentimentAnalysis/blob/master/src/main/resources/logback.xml#L28) as mentioned in logback.xml. You might want to modify it if you want to check the messages.

**Comment by P7h** [comment]
Hi Pablo,

Please could you let me know if you were able to run the code successfully.

Thanks,
Prashanth.
